---
title: KESW2016
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: KESW 2016 Conference
url: http://2016.kesw.ru
markdown: kramdown
highligther: pygments
safe: true
encoding: UTF-8
